class TasksController < ApplicationController
  def index
    city_tasks = Task.where(city_id: current_user.profile.city_id)

    if params[:tab] == "completed"
      @tasks = city_tasks.select { |task| task.completed_by?(current_user) }
    else
      @tasks = city_tasks.reject { |task| task.completed_by?(current_user) }
    end
  end

  def show
    Task.assign_due_dates(current_user.profile)

    @task = Task.includes(:pillar).find_by!(
      id: params[:id],
      city_id: current_user.profile.city_id
    )

    @checklist_items = @task.checklist_items.order(:position)
    item_ids         = @checklist_items.pluck(:id)

    @user_checklist_items = current_user.user_checklist_items
                                        .where(checklist_item_id: item_ids)
                                        .index_by(&:checklist_item_id)

    @manually_unlocked_ids = current_user.user_checklist_items
                                         .where(checklist_item_id: item_ids, manually_unlocked: true)
                                         .pluck(:checklist_item_id).to_set

    pillar_tasks        = Task.where(pillar_id: @task.pillar_id, city_id: @task.city_id).order(:id)
    @task_position      = pillar_tasks.index { |t| t.id == @task.id }.to_i + 1
    @pillar_tasks_count = pillar_tasks.count

    # NOTE: this used to have its own separate, ad-hoc LLM call here (RubyLLM/gpt-4o, a
    # different prompt, only 2 tips, no resource link) that ran instead of TaskInsightsService
    # whenever expert_tips was blank — meaning tips could be generated by two different code
    # paths with two different schemas depending on when/how they were first requested. That
    # was a second, divergent source of truth for the same data. Now there's exactly one path:
    # TaskInsightsService, same schema (title/body/resource_*) every time, whether triggered
    # from here or from the `tasks:generate_expert_tips` rake task.
    if @task.expert_tips.blank?
      tips = TaskInsightsService.new(@task).call
      @task.update(expert_tips: tips) if tips.any?
    end
  end
end
